"use client";

import { PageHead } from "@/components/Layout/PageHead";
import { Footer } from "@/components/Layout/Footer";

const steps = [
  {
    step: "01",
    title: "Getting Started",
    desc: "Clone the repo, copy .env.example to .env.local, fill in your keys, then run: npm install && npm run dev. Walytics boots on localhost:3000.",
    kicker: "First things first",
    bg: "var(--paper)",
  },
  {
    step: "02",
    title: "Tatum Integration",
    desc: "Add TATUM_API_KEY to .env.local. Walytics routes all Sui RPC calls through https://sui-mainnet.gateway.tatum.io — no public node rate limits.",
    kicker: "The RPC backbone",
    bg: "var(--peach)",
  },
  {
    step: "03",
    title: "Walrus Storage",
    desc: "Set WALRUS_PACKAGE_ID in .env.local. Walytics listens for BlobRegistered events on Sui to build a live index of all blobs stored in Walrus.",
    kicker: "Reading the evidence",
    bg: "var(--sticky)",
  },
  {
    step: "04",
    title: "Ask Holmes",
    desc: "Add GEMINI_API_KEY. Head to AI Analytics and ask questions like 'Who are the top publishers?' or 'How is storage trending this week?'",
    kicker: "Interrogate the data",
    bg: "var(--paper-2)",
  },
];

const features = [
  {
    icon: "🔑",
    title: "Tatum Sui RPC",
    desc: "All on-chain reads go through Tatum's enterprise Sui node at sui-mainnet.gateway.tatum.io. Authenticated via TATUM_API_KEY header — fast, reliable, rate-limit-free.",
    bg: "var(--peach)",
  },
  {
    icon: "🦭",
    title: "Walrus Blob Events",
    desc: "Walytics subscribes to BlobRegistered events from the Walrus package on Sui. Each event carries blob ID, size, publisher, and epoch — the raw evidence.",
    bg: "var(--sticky)",
  },
  {
    icon: "🤖",
    title: "Walytics Holmes AI",
    desc: "Gemini 2.0 Flash powers the Holmes chat. The model receives live aggregated metrics as context and answers natural-language questions grounded in real on-chain data.",
    bg: "var(--paper-2)",
  },
  {
    icon: "🔍",
    title: "Blob Explorer",
    desc: "Browse every blob indexed from Walrus. Filter by publisher address, size range, or epoch. Click any row to inspect full blob metadata in the detail panel.",
    bg: "var(--paper)",
  },
  {
    icon: "📈",
    title: "Analytics Dashboard",
    desc: "Real-time totals: blob count, cumulative storage, unique publishers, average blob size. Timeline charts show ingest rate trends across Walrus epochs.",
    bg: "var(--peach)",
  },
  {
    icon: "📋",
    title: "Automated Reports",
    desc: "One-click weekly analytics report: trend summaries, top-publisher breakdowns, and storage anomaly detection — all generated by Holmes from live data.",
    bg: "var(--paper-2)",
  },
];

const stack = [
  { label: "Frontend",   value: "Next.js (App Router)" },
  { label: "Blockchain", value: "Tatum Sui RPC" },
  { label: "Storage",    value: "Walrus Protocol" },
  { label: "AI Engine",  value: "Gemini 2.0 Flash" },
];

const envVars = [
  { key: "TATUM_API_KEY",      desc: "Your Tatum dashboard API key — used in the x-api-key header for all Sui RPC calls." },
  { key: "GEMINI_API_KEY",     desc: "Google AI Studio key — powers the Walytics Holmes chat and automated report generation." },
  { key: "WALRUS_PACKAGE_ID",  desc: "The on-chain package ID of the Walrus protocol — used to filter BlobRegistered events." },
];

const endpoints = [
  { label: "Mainnet RPC",  value: "https://sui-mainnet.gateway.tatum.io" },
  { label: "Method",       value: "suix_queryEvents" },
  { label: "Event filter", value: "{ MoveEventType: '<PACKAGE>::blob_store::BlobRegistered' }" },
  { label: "Auth header",  value: "x-api-key: <TATUM_API_KEY>" },
];

const architecture = [
  { label: "app/api/blobs",      value: "Server route — queries Tatum RPC, returns paginated blob events" },
  { label: "app/api/analytics",  value: "Aggregates raw events into dashboard metrics" },
  { label: "app/api/chat",       value: "Streams Gemini responses with live metrics as system context" },
  { label: "components/Explorer", value: "Client component — filterable blob table + detail panel" },
  { label: "components/Holmes",  value: "Chat UI — sends user prompt to /api/chat, streams reply tokens" },
  { label: "lib/tatum.ts",       value: "Thin RPC client — wraps fetch with Tatum auth header" },
];

export default function TutorialPage() {
  return (
    <div className="page-surface">
      <div className="container" style={{ paddingTop: 0 }}>
        <PageHead
          kicker="Field Manual — Tatum × Walrus Hackathon"
          caseNo="W-0042-TUT"
          title={<>How to Run<br/>the Case.</>}
          lede="A field guide to Walytics — built on Tatum Sui RPC, Walrus decentralized storage, and Gemini AI. Read the evidence. Interrogate the data."
        />

        {/* ── 1. Getting Started ── */}
        <section style={{ marginBottom: 32 }}>
          <div className="kicker" style={{ marginBottom: 8, color: "#fff", fontSize: 16, textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Section 01</div>
          <h2 className="h-display" style={{ fontSize: 30, marginBottom: 24, color: "#fff", textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Getting Started</h2>

          {/* Quick setup steps */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 20, marginBottom: 20 }}>
            {steps.map((s, i) => (
              <div
                key={s.step}
                className="paper-hover animate-on-load jagged-edge"
                style={{
                  background: s.bg,
                  border: "3px solid var(--ink)",
                  boxShadow: "6px 6px 0 0 rgba(0,0,0,0.55)",
                  padding: "20px 22px 30px",
                  animationDelay: `${i * 0.1}s`,
                  transform: `rotate(${(i % 2 === 0 ? 0.4 : -0.4)}deg)`,
                }}
              >
                <div className="kicker" style={{ marginBottom: 10, fontSize: 9 }}>{s.kicker}</div>
                <div style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
                  <span style={{
                    width: 40, height: 40,
                    background: "var(--ink)", color: "var(--tusk)",
                    border: "2px solid var(--ink)",
                    display: "flex", alignItems: "center", justifyContent: "center",
                    fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 18,
                    flexShrink: 0,
                  }}>{s.step}</span>
                  <div>
                    <div className="h-display" style={{ fontSize: 19, marginBottom: 10 }}>{s.title}</div>
                    <p style={{ fontFamily: "var(--font-mono)", fontSize: 13, lineHeight: 1.6, opacity: 0.8, margin: 0 }}>{s.desc}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Env vars table */}
          <div style={{
            background: "var(--surface)",
            border: "3px solid var(--ink)",
            boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
            padding: "20px 24px",
          }}>
            <div className="kicker" style={{ marginBottom: 6 }}>Required Environment Variables</div>
            <div style={{ display: "grid", gap: 10, marginTop: 14 }}>
              {envVars.map((v) => (
                <div key={v.key} style={{
                  display: "grid",
                  gridTemplateColumns: "220px 1fr",
                  gap: 16,
                  background: "var(--paper)",
                  border: "2px solid var(--ink)",
                  boxShadow: "2px 2px 0 0 rgba(0,0,0,0.35)",
                  padding: "10px 14px",
                  alignItems: "center",
                }}>
                  <code className="mono" style={{ fontSize: 12, fontWeight: 700 }}>{v.key}</code>
                  <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.5, opacity: 0.8, margin: 0 }}>{v.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── 2. Tatum Integration ── */}
        <section style={{ marginBottom: 32 }}>
          <div className="kicker" style={{ marginBottom: 8, color: "#fff", fontSize: 16, textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Section 02</div>
          <h2 className="h-display" style={{ fontSize: 30, marginBottom: 24, color: "#fff", textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Tatum Integration</h2>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
            <div style={{
              background: "var(--peach)",
              border: "3px solid var(--ink)",
              boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
              padding: "20px 22px",
            }}>
              <div className="kicker" style={{ marginBottom: 8, fontSize: 9 }}>What Tatum provides</div>
              <div className="h-display" style={{ fontSize: 18, marginBottom: 12 }}>Enterprise Sui RPC</div>
              <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.7, opacity: 0.85, margin: 0 }}>
                Tatum operates managed Sui full nodes with high availability, no rate limits on authenticated keys, and consistent latency.
                Walytics uses a single authenticated client in <code>lib/tatum.ts</code> that injects the <code>x-api-key</code> header on every call — no public node congestion.
              </p>
            </div>

            <div style={{
              background: "var(--paper-2)",
              border: "3px solid var(--ink)",
              boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
              padding: "20px 22px",
            }}>
              <div className="kicker" style={{ marginBottom: 8, fontSize: 9 }}>RPC Endpoints</div>
              <div className="h-display" style={{ fontSize: 18, marginBottom: 12 }}>Connection Details</div>
              <div style={{ display: "grid", gap: 8 }}>
                {endpoints.map((e) => (
                  <div key={e.label} style={{
                    background: "var(--surface)",
                    border: "2px solid var(--ink)",
                    padding: "8px 12px",
                    display: "grid",
                    gridTemplateColumns: "110px 1fr",
                    gap: 10,
                    alignItems: "start",
                  }}>
                    <span className="kicker" style={{ fontSize: 8, marginTop: 2 }}>{e.label}</span>
                    <code className="mono" style={{ fontSize: 11, wordBreak: "break-all", opacity: 0.85 }}>{e.value}</code>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div style={{
            marginTop: 16,
            background: "var(--ink)",
            color: "var(--tusk)",
            border: "3px solid var(--ink)",
            boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
            padding: "18px 22px",
          }}>
            <div className="kicker" style={{ marginBottom: 8, fontSize: 9, opacity: 0.6 }}>Example RPC call (lib/tatum.ts)</div>
            <pre className="mono" style={{ fontSize: 12, lineHeight: 1.7, margin: 0, whiteSpace: "pre-wrap", opacity: 0.9 }}>{`const res = await fetch("https://sui-mainnet.gateway.tatum.io", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "x-api-key": process.env.TATUM_API_KEY!,
  },
  body: JSON.stringify({
    jsonrpc: "2.0", id: 1,
    method: "suix_queryEvents",
    params: [{ MoveEventType: \`\${WALRUS_PACKAGE_ID}::blob_store::BlobRegistered\` }, null, 50, false],
  }),
});`}</pre>
          </div>
        </section>

        {/* ── 3. Walrus Storage ── */}
        <section style={{ marginBottom: 32 }}>
          <div className="kicker" style={{ marginBottom: 8, color: "#fff", fontSize: 16, textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Section 03</div>
          <h2 className="h-display" style={{ fontSize: 30, marginBottom: 24, color: "#fff", textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Walrus Storage</h2>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px,1fr))", gap: 16 }}>
            <div className="paper-hover animate-on-load" style={{
              background: "var(--sticky)",
              border: "3px solid var(--ink)",
              boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
              padding: "20px 22px",
            }}>
              <div style={{ fontSize: 28, marginBottom: 10 }}>🦭</div>
              <div className="h-display" style={{ fontSize: 18, marginBottom: 8 }}>What is Walrus?</div>
              <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.6, opacity: 0.8, margin: 0 }}>
                Walrus is a decentralized blob storage protocol built on Sui. Publishers submit blobs, which are sharded and distributed across storage nodes.
                Blob metadata — ID, size, encoding, epoch — is recorded on-chain as Move events.
              </p>
            </div>

            <div className="paper-hover animate-on-load" style={{
              background: "var(--paper)",
              border: "3px solid var(--ink)",
              boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
              padding: "20px 22px",
              animationDelay: "0.1s",
            }}>
              <div style={{ fontSize: 28, marginBottom: 10 }}>⛓️</div>
              <div className="h-display" style={{ fontSize: 18, marginBottom: 8 }}>The Data Pipeline</div>
              <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.6, opacity: 0.8, margin: 0 }}>
                Walytics calls <code>suix_queryEvents</code> via Tatum RPC, filtering for <code>BlobRegistered</code> events from the Walrus package.
                Each event is parsed, aggregated in memory, and surfaced in the dashboard and explorer — no off-chain database required.
              </p>
            </div>

            <div className="paper-hover animate-on-load" style={{
              background: "var(--peach)",
              border: "3px solid var(--ink)",
              boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
              padding: "20px 22px",
              animationDelay: "0.2s",
            }}>
              <div style={{ fontSize: 28, marginBottom: 10 }}>📦</div>
              <div className="h-display" style={{ fontSize: 18, marginBottom: 8 }}>Blob Fields</div>
              <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.6, opacity: 0.8, margin: 0 }}>
                Each <code>BlobRegistered</code> event exposes: <strong>blob_id</strong>, <strong>size</strong> (bytes),
                <strong>publisher</strong> address, <strong>epoch</strong>, and <strong>storage_type</strong>.
                These fields drive every chart, filter, and AI insight in Walytics.
              </p>
            </div>

            <div className="paper-hover animate-on-load" style={{
              background: "var(--paper-2)",
              border: "3px solid var(--ink)",
              boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
              padding: "20px 22px",
              animationDelay: "0.3s",
            }}>
              <div style={{ fontSize: 28, marginBottom: 10 }}>🔄</div>
              <div className="h-display" style={{ fontSize: 18, marginBottom: 8 }}>Dogfooding</div>
              <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.6, opacity: 0.8, margin: 0 }}>
                Generated analytics reports are written back to Walrus as blobs — creating an immutable, on-chain audit trail of the metrics themselves.
                Walytics watches itself.
              </p>
            </div>
          </div>
        </section>

        {/* ── 4. AI Analytics ── */}
        <section style={{ marginBottom: 32 }}>
          <div className="kicker" style={{ marginBottom: 8, color: "#fff", fontSize: 16, textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Section 04</div>
          <h2 className="h-display" style={{ fontSize: 30, marginBottom: 24, color: "#fff", textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>AI Analytics — Walytics Holmes</h2>

          <div style={{
            background: "var(--ink)",
            color: "var(--tusk)",
            border: "3px solid var(--ink)",
            boxShadow: "6px 6px 0 0 rgba(0,0,0,0.6)",
            padding: "24px 28px",
            marginBottom: 16,
          }}>
            <div className="kicker" style={{ marginBottom: 8, fontSize: 9, opacity: 0.6 }}>The Detective</div>
            <div className="h-display" style={{ fontSize: 22, marginBottom: 14 }}>Powered by Gemini 2.0 Flash</div>
            <p style={{ fontFamily: "var(--font-mono)", fontSize: 13, lineHeight: 1.7, opacity: 0.85, margin: "0 0 16px" }}>
              Walytics Holmes is a Gemini 2.0 Flash agent that receives the current aggregated Walrus metrics as system context on every chat turn.
              The model reasons over real on-chain data — blob counts, storage totals, publisher rankings, epoch trends — and answers in natural language.
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px,1fr))", gap: 12 }}>
              {[
                { q: "Who are the top publishers?", tag: "Publisher ranking" },
                { q: "What is the average blob size?", tag: "Size stats" },
                { q: "How is storage trending this week?", tag: "Trend analysis" },
                { q: "Generate a weekly report", tag: "Auto report" },
              ].map((ex) => (
                <div key={ex.q} style={{
                  background: "rgba(255,255,255,0.06)",
                  border: "1px solid rgba(255,255,255,0.2)",
                  padding: "10px 14px",
                }}>
                  <div className="kicker" style={{ fontSize: 8, opacity: 0.5, marginBottom: 4 }}>{ex.tag}</div>
                  <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, margin: 0, opacity: 0.8, fontStyle: "italic" }}>"{ex.q}"</p>
                </div>
              ))}
            </div>
          </div>

          <div style={{
            background: "var(--paper)",
            border: "3px solid var(--ink)",
            boxShadow: "4px 4px 0 0 rgba(0,0,0,0.45)",
            padding: "18px 22px",
          }}>
            <div className="kicker" style={{ marginBottom: 6 }}>How it works</div>
            <p style={{ fontFamily: "var(--font-mono)", fontSize: 13, lineHeight: 1.7, opacity: 0.85, margin: 0 }}>
              The <code>/api/chat</code> route fetches fresh aggregated metrics from the Walrus event index, serialises them into a structured system prompt,
              then streams the Gemini response back to the client. The AI has no stale training knowledge of Walrus state — every answer is grounded in the
              latest on-chain data pulled through Tatum RPC.
            </p>
          </div>
        </section>

        {/* ── 5. Blob Explorer ── */}
        <section style={{ marginBottom: 32 }}>
          <div className="kicker" style={{ marginBottom: 8, color: "#fff", fontSize: 16, textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Section 05</div>
          <h2 className="h-display" style={{ fontSize: 30, marginBottom: 24, color: "#fff", textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Blob Explorer</h2>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 }}>
            {[
              { icon: "🗂️", title: "Browse All Blobs", desc: "Paginated table of every BlobRegistered event indexed from Walrus. Sorted by recency by default. Shows blob ID, size, publisher, and epoch.", bg: "var(--peach)" },
              { icon: "🔎", title: "Filter & Search", desc: "Filter by publisher address to see storage from a specific actor. Filter by size range to find large or small blobs. Combine filters freely.", bg: "var(--sticky)" },
              { icon: "🧾", title: "Blob Detail Panel", desc: "Click any row to open the detail panel. See full blob_id, raw size in bytes and human-readable format, epoch number, and storage type classification.", bg: "var(--paper-2)" },
              { icon: "📊", title: "Per-blob Analytics", desc: "The explorer feeds selected blob data into Holmes. Ask targeted questions about a specific publisher or size cohort directly from the explorer view.", bg: "var(--paper)" },
            ].map((f, i) => (
              <div key={f.title} className="paper-hover animate-on-load" style={{
                background: f.bg,
                border: "3px solid var(--ink)",
                boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
                padding: "18px 20px",
                animationDelay: `${0.4 + i * 0.08}s`,
              }}>
                <div style={{ fontSize: 28, marginBottom: 10 }}>{f.icon}</div>
                <div className="h-display" style={{ fontSize: 18, marginBottom: 8 }}>{f.title}</div>
                <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.6, opacity: 0.8, margin: 0 }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ── 6. Architecture ── */}
        <section style={{ marginBottom: 32 }}>
          <div className="kicker" style={{ marginBottom: 8, color: "#fff", fontSize: 16, textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Section 06</div>
          <h2 className="h-display" style={{ fontSize: 30, marginBottom: 24, color: "#fff", textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Architecture</h2>

          {/* Tech stack */}
          <div style={{
            background: "var(--surface)",
            border: "4px solid var(--ink)",
            boxShadow: "6px 6px 0 0 rgba(0,0,0,0.6)",
            padding: "24px 26px",
            marginBottom: 16,
          }}>
            <div className="kicker" style={{ marginBottom: 6 }}>Under the Magnifying Glass</div>
            <h3 className="h-display" style={{ fontSize: 20, marginBottom: 16 }}>Tech Stack</h3>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px,1fr))", gap: 14 }}>
              {stack.map((s) => (
                <div key={s.label} style={{
                  background: "var(--paper-2)",
                  border: "2px solid var(--ink)",
                  boxShadow: "3px 3px 0 0 rgba(0,0,0,0.4)",
                  padding: "12px 16px",
                }}>
                  <div className="kicker" style={{ fontSize: 9 }}>{s.label}</div>
                  <div className="mono" style={{ fontSize: 13, fontWeight: 700, marginTop: 6 }}>{s.value}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Component map */}
          <div style={{
            background: "var(--paper)",
            border: "3px solid var(--ink)",
            boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
            padding: "20px 24px",
          }}>
            <div className="kicker" style={{ marginBottom: 6 }}>Component Map</div>
            <div style={{ display: "grid", gap: 8, marginTop: 12 }}>
              {architecture.map((a) => (
                <div key={a.label} style={{
                  display: "grid",
                  gridTemplateColumns: "200px 1fr",
                  gap: 16,
                  background: "var(--peach)",
                  border: "2px solid var(--ink)",
                  boxShadow: "2px 2px 0 0 rgba(0,0,0,0.3)",
                  padding: "10px 14px",
                  alignItems: "center",
                }}>
                  <code className="mono" style={{ fontSize: 11, fontWeight: 700 }}>{a.label}</code>
                  <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.5, opacity: 0.8, margin: 0 }}>{a.value}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── 7. Resources ── */}
        <section style={{ marginBottom: 32 }}>
          <div className="kicker" style={{ marginBottom: 8, color: "#fff", fontSize: 16, textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Section 07</div>
          <h2 className="h-display" style={{ fontSize: 30, marginBottom: 20, color: "#fff", textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Resources</h2>

          <div style={{
            background: "var(--paper-2)",
            border: "3px solid var(--ink)",
            boxShadow: "4px 4px 0 0 rgba(0,0,0,0.5)",
            padding: "20px 24px",
            display: "flex", gap: 12, flexWrap: "wrap",
            marginBottom: 16,
          }}>
            <a href="https://docs.tatum.io" target="_blank" rel="noopener noreferrer"
               className="btn" style={{ padding: "10px 16px", fontSize: 13 }}>Tatum Docs →</a>
            <a href="https://tatum.io/mcp" target="_blank" rel="noopener noreferrer"
               className="btn btn-ghost" style={{ padding: "10px 16px", fontSize: 13 }}>Tatum MCP →</a>
            <a href="https://docs.wal.app" target="_blank" rel="noopener noreferrer"
               className="btn btn-ghost" style={{ padding: "10px 16px", fontSize: 13 }}>Walrus Docs →</a>
            <a href="https://docs.sui.io" target="_blank" rel="noopener noreferrer"
               className="btn btn-ghost" style={{ padding: "10px 16px", fontSize: 13 }}>Sui Docs →</a>
            <a href="https://ai.google.dev/gemini-api/docs" target="_blank" rel="noopener noreferrer"
               className="btn btn-ghost" style={{ padding: "10px 16px", fontSize: 13 }}>Gemini API Docs →</a>
            <a href="https://github.com/EdCryptoFi/Walytics" target="_blank" rel="noopener noreferrer"
               className="btn btn-ghost" style={{ padding: "10px 16px", fontSize: 13 }}>GitHub Repo →</a>
          </div>

          <div style={{
            background: "var(--sticky)",
            border: "3px solid var(--ink)",
            boxShadow: "4px 4px 0 0 rgba(0,0,0,0.45)",
            padding: "16px 20px",
          }}>
            <div className="kicker" style={{ marginBottom: 6, fontSize: 9 }}>Hackathon track</div>
            <p style={{ fontFamily: "var(--font-mono)", fontSize: 13, lineHeight: 1.6, opacity: 0.85, margin: 0 }}>
              Walytics was built for the <strong>Tatum × Walrus hackathon</strong>. It demonstrates end-to-end use of Tatum enterprise Sui RPC nodes
              for on-chain analytics, Walrus decentralized storage as both a data source and write target, and Gemini AI as an intelligent query layer
              over live blockchain data.
            </p>
          </div>
        </section>

        {/* Features overview strip */}
        <section style={{ marginBottom: 32 }}>
          <div className="kicker" style={{ marginBottom: 8, color: "#fff", fontSize: 16, textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Capabilities</div>
          <h2 className="h-display" style={{ fontSize: 30, marginBottom: 24, color: "#fff", textShadow: "1px 1px 4px rgba(0,0,0,0.7)" }}>Feature Overview</h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 }}>
            {features.map((f, i) => (
              <div key={f.title} className="paper-hover animate-on-load" style={{
                background: f.bg,
                border: "3px solid var(--ink)",
                boxShadow: "5px 5px 0 0 rgba(0,0,0,0.5)",
                padding: "18px 20px",
                animationDelay: `${0.4 + i * 0.08}s`,
              }}>
                <div style={{ fontSize: 28, marginBottom: 10 }}>{f.icon}</div>
                <div className="h-display" style={{ fontSize: 18, marginBottom: 8 }}>{f.title}</div>
                <p style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.6, opacity: 0.8, margin: 0 }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <Footer/>
      </div>
    </div>
  );
}
